---
# BIG-IP SSHログイン設定
ansible_ssh_user: root
ansible_ssh_pass: [rootパスワード]

# BIG-IP GUIログイン設定
bigip_user: admin
bigip_password: [adminパスワード]
bigip_delegate_to: localhost

# Provider設定
bigip_provider:
  server: "{{ bigip_server }}"
  user: "{{ bigip_user }}"
  password: "{{ bigip_password }}"
  server_port: 443
  validate_certs: no

# Managementポートのルーティング設定
bigip_management_route:
  - { name: "default", description: "Default Route", gateway: "192.168.56.1", network: "0.0.0.0/0" }

# インタフェース設定
bigip_interface:
  - { untagged_interface: "external_trunk", name: "external", tag: "10" }
  - { untagged_interface: "internal_trunk", name: "internal", tag: "20" }
  - { untagged_interface: "1.3", name: "ha", tag: "30" }

# DNS設定
bigip_dns:
  - { name_servers: ["8.8.8.8", "8.8.4.4"] }

# NTP設定
bigip_ntp:
  - { ntp_servers: ["ntp.nict.jp", "time.google.com"], timezone: "Asia/Tokyo" }

# 負荷分散ノード設定
bigip_node:
  - { name: "web01", description: "Web Server 1", host: "10.2.0.10", monitors: ["/Common/icmp"], ratio: "1", connection_limit: "0", rate_limit: "0" }
  - { name: "web02", description: "Web Server 2", host: "10.2.0.11", monitors: ["/Common/icmp"], ratio: "1", connection_limit: "0", rate_limit: "0" }

# 負荷分散プール設定
bigip_pool:
  - { name: "web_pool", description: "Web Server Pool", monitors: ["/Common/http"], lb_method: "round-robin", priority_group_activation: "0" }

# 負荷分散プールメンバ設定
bigip_pool_member:
  - { pool: "web_pool", port: "80", host: "10.2.0.10", name: "web01" }
  - { pool: "web_pool", port: "80", host: "10.2.0.11", name: "web02" }

# Virtual Server設定
bigip_virtual_server:
  - { name: "web_vs1", description: "Virtual Server 1", destination: "10.1.0.10", port: "80", pool: "web_pool", enabled_vlans: "all", snat: "Automap", profiles: ["http"] }

# Trunk設定
bigip_trunk:
  - { name: "external_trunk", description: "", interfaces: ["1.1"], link_selection_policy: "auto", frame_distribution_hash: "source-destination-ip", lacp_enabled: "yes", lacp_mode: "active", lacp_timeout: "long"  }
  - { name: "internal_trunk", description: "", interfaces: ["1.2"], link_selection_policy: "auto", frame_distribution_hash: "source-destination-ip", lacp_enabled: "yes", lacp_mode: "active", lacp_timeout: "long"  }

# SelfIP設定(Floating IP)
bigip_floatip:
  - { name: "external_VIP", address: "10.1.0.254", netmask: "255.255.255.0", vlan: "external", allow_service: "none", traffic_group: "traffic-group-1" }
  - { name: "internal_VIP", address: "10.2.0.254", netmask: "255.255.255.0", vlan: "internal", allow_service: "none", traffic_group: "traffic-group-1" }

# 冗長化設定(device trust)
bigip_device_trust:
  - { peer_server: "192.168.56.102", peer_hostname: "bigip02.example.com" }

# 冗長化設定(device group)
bigip_device_group:
  - { name: "device_group", description: "device_group", full_sync: "no", save_on_auto_sync: "no" }

# 冗長化設定(device group member)
bigip_device_group_member:
  - { name: "bigip01.example.com", device_group: "device_group" }
  - { name: "bigip02.example.com", device_group: "device_group" }

# 冗長化設定(config sync)
bigip_configsync_action:
  - { device_group: "device_group" }

# 冗長化設定(HA Group設定)
bigip_device_ha_group:
  - { name: "HA_Group", active_bonus: "10" }

bigip_ha_pool:
  - pools:
     - pool_name: "web_pool"
       weight: "10"
       minimum_threshold: "1"

bigip_ha_trunk:
  - trunks:
     - trunk_name: "external_trunk"
       weight: "10"
       minimum_threshold: "1"
     - trunk_name: "internal_trunk"
       weight: "10"
       minimum_threshold: "1"

# 冗長化設定(traffic group)
bigip_device_traffic_group:
  - { name: "traffic-group-1", ha_group: "HA_Group" }

