---
# tasks file for setup_desktop-rootlogin
- name: AllowRoot設定
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "^AllowRoot"
    insertafter: "^\\[security\\]"
    line: "AllowRoot=true"

- name: gdm-password pam_succeed_ifコメントアウト
  replace:
    path: /etc/pam.d/gdm-password
    regexp: "^auth\trequired\tpam_succeed_if.so"
    replace: "#auth\trequired\tpam_succeed_if.so"

- name: rootパスワード設定
  user:
    name: "root"
    password: "{{ root_pass }}"

